# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpxobject',
            name='accuracygraph',
            field=models.ImageField(null=True, upload_to='accuracy/'),
        ),
        migrations.AddField(
            model_name='gpxobject',
            name='speedgraph',
            field=models.ImageField(null=True, upload_to='speed/'),
        ),
        migrations.AlterField(
            model_name='gpxobject',
            name='uploadDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
