# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpx', '0002_auto_20170809_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpxobject',
            name='xmlfile',
            field=models.FileField(null=True, upload_to='xml/'),
        ),
    ]
